begin
	raise
rescue Exception => e
	puts "Error is generated"
end